# Basic Site Settings
locale                   : "fr-FR"
title                    : "Anas SGHURI"
title_separator          : "—"
name                     : "Anas Sghuri"
description              : "Docteur-ingénieur  en Sciences des Matériaux"
url                      : "https://anas-sg-git.github.io"
baseurl                  : "/anas-sghuri"
repository               : "Anas-Sg-git/anas-sghuri"

# ── Section "Site Author" ────────────────────────────────────
author:
  avatar           : "profile.png"
  name             : "SGHURI Anas"
  pronouns         : ""
  bio              : "Docteur-ingénieur en Sciences des Matériaux"
  location         : "Poitiers, France"
  employer         : "Univ. de Poitiers \nISAE-ENSMA \nInstitut Pprime"
  email            : "anas.sghuri@gmail.com"
 
  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=qvDI3ZYAAAAJ&hl=fr"
  orcid            : "https://orcid.org/0009-0001-5294-6215"
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=58509006000"
 
  # Social
  github           : "Anas-Sg-git"
